#!/bin/bash
service_script=rf24
app=rf24_proxy.py
if [[ $EUID -ne 0 ]]; then
  echo you are not root. Use sudo.
  exit 2
fi

cp $service_script /etc/init.d/
chmod +x /etc/init.d/${service_script}

# devices and commands configurations
if [ -f rf24_proxy.conf ]; then
  cp rf24_proxy.conf /etc/
fi

tgtdir=/usr/local/rf24_proxy/
#https://github.com/cz6ace/arduino_rpi_openhab.git
mkdir -p $tgtdir
#cp $app $tgt/
ln -s ${PWD}${app} ${tgtdir}/${app}
touch /etc/rf24_proxy.conf
# enable init script
update-rc.d rf24 defaults
echo done.
